# Generated by Django 4.2.1 on 2023-05-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0003_product_is_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductWithUser',
        ),
    ]
