# Generated by Django 4.2 on 2023-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Handle', models.CharField(blank=True, max_length=400, null=True)),
                ('Title', models.CharField(max_length=400)),
                ('Body', models.TextField(blank=True, max_length=400, null=True)),
                ('Vendor', models.CharField(blank=True, max_length=400, null=True)),
                ('Type', models.CharField(blank=True, max_length=400, null=True)),
                ('Tags', models.CharField(blank=True, max_length=400, null=True)),
                ('Published', models.CharField(blank=True, max_length=400, null=True)),
                ('Variant_SKU', models.CharField(blank=True, max_length=400, null=True)),
                ('Variant_Inventory_Tracker', models.CharField(blank=True, max_length=400, null=True)),
                ('Variant_Price', models.CharField(blank=True, max_length=400, null=True)),
                ('Image_Src', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
